### ISSUE TITLE
原生小程序怎样使用  api方法，列如get方法，似乎不能使用

### ISSUE THREAD

**Issue by huhaoyang** [charleslo1/weapp-cookie#10]

**Comment by charleslo1** [comment]
使用 npm 安装
npm install weapp-cookie --save

# 将 npm 包复制到 vendor 文件夹，避免小程序可能不能找到文件（tips：使用 wepy/mpvue 等框架无需此步）
cp -rf ./node_modules/ ./vendor/
在小程序根目录的 app.js 一行代码引入即可
// app.js
import cookies from './vendor/weapp-cookie/dist/weapp-cookie'

// tips: 使用 wepy/mpvue 可以直接在入口 js 引入 weapp-cookie 模块
// import cookies from 'weapp-cookie'

App({
    onLaunch: function () {
        // use get
        const token = cookies.get('token')
    }
    // ...
})

**Comment by charleslo1** [comment]
按照 README 使用应该是没问题的

### 使用 npm 安装
```
npm install weapp-cookie --save

// 将 npm 包复制到 vendor 文件夹，避免小程序可能不能找到文件（tips：使用 wepy/mpvue 等框架无需此步）
cp -rf ./node_modules/ ./vendor/
```

### 在小程序根目录的 app.js 一行代码引入即可
```
// app.js
import cookies from './vendor/weapp-cookie/dist/weapp-cookie'

// tips: 使用 wepy/mpvue 可以直接在入口 js 引入 weapp-cookie 模块
// import cookies from 'weapp-cookie'

App({
    onLaunch: function () {
        // use get
        const token = cookies.get('token')
    }
    // ...
})
```

**Comment by Damocs0921** [comment]
<img width="1021" alt="d2dc02a1-68d2-4575-939b-21baf1ddde03" src="https://user-images.githubusercontent.com/7037269/50590882-bd605a80-0ec7-11e9-9d58-3d554c377546.png">
