### ISSUE TITLE
mac上开发时没问题，但是到手机上真机调试时就报错了

### ISSUE THREAD

**Issue by machao1990** [charleslo1/weapp-cookie#13]
这是报错信息：
![image](https://user-images.githubusercontent.com/17400576/50282218-00184080-048d-11e9-8273-473269bcb9ed.png)

这是我的引入方式：
![image](https://user-images.githubusercontent.com/17400576/50282084-9bf57c80-048c-11e9-8f80-2a3abfcecd85.png)

**Comment by charleslo1** [comment]
你好，这是微信小程序运行时自身的问题，已知受影响的机型有：华为荣耀v9，小米max2，微信版本均为6.7.3，请等待官方修复后升级微信即可解决。

> https://developers.weixin.qq.com/community/develop/doc/0000a065a44df8548d974931a5b800?highLine=setStorageSync%253Afail%2520Error%253A%2520Failed%2520To%2520Send%2520Sync

> https://developers.weixin.qq.com/community/develop/doc/00086c705f4ac83cd3b7dba195b000?highLine=setStorageSync%253Afail%2520Error%253A%2520Failed%2520To%2520Send%2520Sync
