### ISSUE TITLE
泛域名的cookie 查询失败

### ISSUE THREAD

**Issue by CupNoodleFork** [charleslo1/weapp-cookie#14]
a.xxx.com把cookie 种在了 domain:xxx.com, 接下来请求b.xxx.com 的时候不会带上cookie, requestProxy 中对domain的处理兼容性不好

**Comment by CupNoodleFork** [comment]
好像是util.getCookieScopeDomain 这个兼容的姿势不对的样子

**Comment by charleslo1** [comment]
泛域名或子域名之间进行 cookie 共享时需要将 domain 设置为父域名: .xxx.dom（注意前面的点），尝试让后端调整共享 cookie 的域名设置
### 示例：
``` js
response.setCookie('sid', 'xxx', {
   path: '/',
   domain: '.xxx.com'    // 注意前面的点
})
```
