### ISSUE TITLE
wx.request 返回值被你干没了

### ISSUE THREAD

**Issue by a573367014** [charleslo1/weapp-cookie#15]
https://developers.weixin.qq.com/miniprogram/dev/api/RequestTask.html
这些方法就无法使用了

**Comment by a573367014** [comment]
https://developers.weixin.qq.com/miniprogram/dev/api/RequestTask.html
这些方法就无法使用了

**Comment by charleslo1** [comment]
谢谢反馈，这个问题已经修复了
