### ISSUE TITLE
接收到的cookie和传过去的cookie不一致

### ISSUE THREAD

**Issue by zlipeng** [charleslo1/weapp-cookie#26]
接收到的cookie是`mXSPmPD_QGg9pwZpTnk-K6fw1qBtZAWW-8PdJMZ9zmbTGU-uHnQK5khGbiJZkHYcdWzj_0ysqJVQHm_8V6op8g==`，

但接下去get请求传过去的cookie是`mXSPmPD_QGg9pwZpTnk-K6fw1qBtZAWW-8PdJMZ9zmbTGU-uHnQK5khGbiJZkHYcdWzj_0ysqJVQHm_8V6op8g%3D%3D`。

最后的两个==被转码了。

**Comment by teabyii** [comment]
这个问题怎么解决的？

**Comment by charleslo1** [comment]
谢谢反馈，该问题已经解决，请更新到最新版本
