### ISSUE TITLE
BUG:响应头出现多个set-cookie时，只有最后一个被保存

### ISSUE THREAD

**Issue by pick30** [charleslo1/weapp-cookie#28]
BUG:响应头出现多个set-cookie时，只有最后一个被保存

**Comment by pick30** [comment]
(Status-Line):HTTP/1.1 200 OK
Cache-Control:private
Content-Type:text/plain; charset=utf-8
Server:Microsoft-IIS/8.5
X-AspNetMvc-Version:5.0
X-AspNet-Version:4.0.30319
Set-Cookie:c3=1230; domain=/site; expires=Fri, 12-Jul-2019 01:37:01 GMT; path=/
Set-Cookie:c4=1230; path=/
X-Powered-By:ASP.NET
Date:Wed, 10 Jul 2019 01:37:01 GMT
Connection:close
Content-Length:2

上述响应头部，包含两个Set-Cookie，下次请求时，发现只带上了c4，c3被丢弃？？

**Comment by charleslo1** [comment]
你好，请问是在微信小程序环境吗？我测试了一下，微信小程序环境下的响应头 set-cookie 值是会合并为一行的

**Comment by charleslo1** [comment]
```
Set-Cookie:c3=1230; domain=/site; expires=Fri, 12-Jul-2019 01:37:01 GMT; path=/
Set-Cookie:c4=1230; path=/
```

我看了您的 set-cookie 字段，有以下两种可能导致 c3 未被发送：
1. c3 的 domain 设置不正确导致 cookie 被过滤
2. c3 的 expires 已过期

您可以重新设置一下这两个属性试试
