### ISSUE TITLE
domain的set规则问题和cookie编码问题

### ISSUE THREAD

**Issue by LarenDorr** [charleslo1/weapp-cookie#29]
1、如 https://github.com/charleslo1/weapp-cookie/issues/14 所说，我也遇到了这个问题，但是我们原先web(微网页)情况下是没问题的，发现web环境时，后端返回的`domain字`段即使为：`xxx.com`，浏览器也会将其自动设置为 `.xxx.com`。但是你的规则与浏览器的不一样，所以带不上cookie。
2、我们的value中有@这个字符，发现被encode了，接收时和发送时不一致，发现了这个commit：https://github.com/charleslo1/weapp-cookie/commit/e21617e3c2d787f0df1832993c186846d684f9a9 在发送时应该要decode啊，而且中文cookie值这个想不出来为什么会干这种事...是否编码也可以提供个选项出来啊

**Comment by charleslo1** [comment]
谢谢反馈，针对问题 1 我查了一些资料，加点是 RFC 2109 标准，最新标准是 RFC 6265，也许浏览器为了兼容适配旧的标准会将 xxx.com 自动设置为 .xxx.com，目前已修改这部分逻辑和浏览器保持一致。然后之前解决问题 2 的时候确实有欠考虑，一般有中文的情况应该由后端来控制编码和解码，所以这部分代码也已经去除。
