### ISSUE TITLE
Cookie 中文

### ISSUE THREAD

**Issue by sc419** [charleslo1/weapp-cookie#30]
Cookie 包含中文时候， 微信小程序 开发工具提示。 request:fail Failed to execute 'setRequestHeader' on 'XMLHttpRequest': Value is not a valid ByteString.

客户端 并未操作 Cookie, Cookie 操作全在 服务器

**Comment by sc419** [comment]
Cookie 包含中文时候， 微信小程序 开发工具提示。 request:fail Failed to execute 'setRequestHeader' on 'XMLHttpRequest': Value is not a valid ByteString.

客户端 并未操作 Cookie, Cookie 操作全在 服务器

**Comment by charleslo1** [comment]
你好，Cookie 通常不允许存储中文值，当 Cookie 值包含中文的时候请在后端对中文值进行编码解码即可

**Comment by sc419** [comment]
> 你好，Cookie 通常不允许存储中文值，当 Cookie 值包含中文的时候请在后端对中文值进行编码解码即可

后台已经自动编码，开发工具看到的 Network 看到的 返回头部含有 `Set-Cookie: wyBcvNLD_USERNAME=%E5%AD%99%E5%A4%A7%E7%88%B7; expires=Fri, 16-Aug-2019 20:22:08 GMT; path=/` 其中 `***_USERNAME` 的值是经过 urlencode 编码的中文。
现在只要返回这个 Cookie 以后请求都提示 `request:fail Failed to execute 'setRequestHeader' on 'XMLHttpRequest': Value is not a valid ByteString.`

**Comment by charleslo1** [comment]
请问是在微信小程序环境吗？

**Comment by sc419** [comment]
> 请问是在微信小程序环境吗？

是的 还没上线，在微信的开发工具里面报错。
[恢复这处后好了](https://github.com/charleslo1/weapp-cookie/commit/da3b65b7696216007fdbaf1bbe33155b4bdf414c#diff-f13bd7e589bed259716b5cbb686d58cdL1697) 暂时这样能用。

**Comment by charleslo1** [comment]
我这边刚有测试过，后端如果设置 cookie 时有对值进行 urlencode，前端是可以正常接收和发送的。如果还有问题可以扫描我头像加我微信方便交流哈
