### ISSUE TITLE
cookie  key 一样 咋没有覆盖旧的值

### ISSUE THREAD

**Issue by Blizzard-liu** [charleslo1/weapp-cookie#31]
![image](https://user-images.githubusercontent.com/20244432/67999811-b2698880-fc98-11e9-8c8c-cc85d1ee003f.png)
![image](https://user-images.githubusercontent.com/20244432/67999835-c44b2b80-fc98-11e9-99fd-a9ad4f41130c.png)

**Comment by Blizzard-liu** [comment]
![image](https://user-images.githubusercontent.com/20244432/67999907-05434000-fc99-11e9-8e0e-08d9240577a6.png)

**Comment by charleslo1** [comment]
您这个是哪个平台的小程序？这应该不是这个库设置的 cookie，大多数小程序平台是没有 Cookie 的，weapp-cookie 只是使用 Storage 模拟了 Cookie

**Comment by Blizzard-liu** [comment]
微信的 就是用这个库  保存的时候key 一样 旧值没有覆盖吗 还可以取出来放cookie里面

**Comment by charleslo1** [comment]
可以把设置 cookie 的代码（前端 OR 后端）贴出来吗？

**Comment by Blizzard-liu** [comment]
啥都没干 我就按你的文档说明做的  只是后来 token值换了几次  key也换了

**Comment by Blizzard-liu** [comment]
然后通过微信开发工具查看的cookie  好多个

**Comment by charleslo1** [comment]
我这边测试过是没找到问题的，有需要可以扫一下我的头像二维码帮您解决下哈
