### ISSUE TITLE
[Bug Report] 源码中对responseCookies解析存在兼容问题

### ISSUE THREAD

**Issue by suguoyao** [charleslo1/weapp-cookie#39]
比如当Response Headers中存在多个Set-cookie时：

```
Set-Cookie: key1=value1; domain=/site; expires=Fri, 12-Jul-2019 01:37:01 GMT; path=/; secure
Set-Cookie: key2=value2; domain=/site; expires=Fri, 12-Jul-2019 01:37:01 GMT; path=/; secure
```

weapp-cookie.js源码第2400行中：
```
...

// 请求成功回调
      var successCallback = options.success;
      options.success = function (response) {
        response.header = response.header || response.headers;
        // 获取响应 cookies
        var responseCookies = response.header ? response.header['Set-Cookie'] || response.header['set-cookie'] : '';
        // 设置 cookies，以便下次请求带上
        if (responseCookies) cookieStore.setResponseCookies(responseCookies, domain);
        // 调用成功回调函数
        successCallback && successCallback(response);
      };

...
```

目前发现，在QQ小程序下，IOS设备正常，但安卓设备下读取的responseCookies格式与IOS设备不一致，导致后续一系列的parse等解析出现异常，造成安卓设备无法使用该库，原因如下：

IOS设备下调试QQ小程序，就以上headers数据来说，responseCookies返回的是：
```
"key1=value1; domain=/site; expires=Fri, 12-Jul-2019 01:37:01 GMT; path=/; secure,key2=value2; domain=/site; expires=Fri, 12-Jul-2019 01:37:01 GMT; path=/; secure"
```
> 注意：IOS下这里多个cookie之间是以逗号拼接的，这是正确的情况

而Android设备下调试QQ小程序，responseCookies返回的是：
```
"key1=value1; domain=/site; expires=Fri, 12-Jul-2019 01:37:01 GMT; path=/; secure;key2=value2; domain=/site; expires=Fri, 12-Jul-2019 01:37:01 GMT; path=/; secure"
```

> 注意：这里多个cookie之间的拼接和ios不一致，是以分号拼接，`secure;key2=value2;`

所以，需要在这里对responseCookies进行一个兼容处理，将分号替换成逗号，不然后续的`parseString`或`splitCookiesString`都将无法返回正确的结果。

目前我的临时解决方案是在读取到responseCookies后，加上：
```
if (typeof responseCookies === 'string') {
   responseCookies = responseCookies.replace(/secure;/g, 'secure,');
}
```
但考虑到不一定是以secure结尾，所以要按情况来判断

**Comment by charleslo1** [comment]
多谢反馈，已解决，请更新到最新版本

**Comment by eric-gitta-moore** [comment]
您好，这里我发现匹配到其他指令的时候会出现问题，导致多出几个cookie
例如：
`JSESSIONID=A9118060632F0DA9A0B967ADC35DF903; Path=/; HttpOnly, route=38ac858752aa1b02deb40f6abc4d204f;Path=/` 
正则后结果：
`JSESSIONID=A9118060632F0DA9A0B967ADC35DF903; Path=/; HttpOnly, route=38ac858752aa1b02deb40f6abc4d204f,Path=/`

`acw_tc=2760826116537529404556885ef39627d3deaeb2cb846ffa2d5826295c84e8,path=/;HttpOnly,Max-Age=1800`
正则后结果：
`acw_tc=2760826116537529404556885ef39627d3deaeb2cb846ffa2d5826295c84e8,path=/,HttpOnly,Max-Age=1800`

这里我提供一个我的想法：
`/\;((?!Path|Expires|Max-Age|Domain|Path|SameSite)[^\s\;]*?)\=/gi`
这个正则既可以解决楼上的问题还可以避免误杀其他指令
