### ISSUE TITLE
name 和 options.domain 值不正确！

### ISSUE THREAD

**Issue by orchie** [charleslo1/weapp-cookie#47]
![image](https://user-images.githubusercontent.com/29848298/91626734-70a68d00-e9e4-11ea-9bda-c9fa6b00308e.png)
我是在 小程序插件 里使用的 
因为现在小程序已经原生支持npm
所以按照官方的方式 安装 插件
https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html
目录 /plugin/index.js
```
const cookies = require('weapp-cookie')
cookies.set("test", 100)
```
热编译报错

是否不能支持在小程序插件里使用?

**Comment by charleslo1** [comment]
你好，是因为你没有设置域名哦。小程序不同于Web网站有访问默认域名，所以在小程序中设置 cookie 的时必须手动设定需要将 Cookie 值写入哪个域名，你改为下面的写法就不会报错了：
``` js
const cookies = require('weapp-cookie')
cookies.set("test", 100, { domain: 'xxx.com' })
```
