### ISSUE TITLE
"vendor/weapp-cookie/src/set-cookie-parser.js" is not defined

### ISSUE THREAD

**Issue by YeDaxia** [charleslo1/weapp-cookie#7]
**错误信息：**

VM27347:1 Error: module "vendor/weapp-cookie/src/set-cookie-parser.js" is not defined
    at require (WAService.js:18)
    at WAService.js:18
    at Cookie.js? [sm]:1
    at require (WAService.js:18)
    at WAService.js:18
    at CookieStore.js? [sm]:1
    at require (WAService.js:18)
    at WAService.js:18
    at cookieShim.js? [sm]:1
    at require (WAService.js:18)

**app.js：**

import './vendor/weapp-cookie/index'

**项目结构：**
![image](https://user-images.githubusercontent.com/4317015/46203503-91738d00-c34c-11e8-9d8c-09ae997ec70b.png)

**Comment by charleslo1** [comment]
直接引用 dist/weapp-cookie.js 吧

```
// app.js
import './vendor/weapp-cookie/dist/weapp-cookie'

App({
    onLaunch: function () { }
    // ...
})
``
