### ISSUE TITLE
小程序引入插件时，wx.request 重写报错

### ISSUE THREAD

**Issue by vellow** [charleslo1/weapp-cookie#8]
可以支持插件吗，
提供一个配置项，config(requestName: "requestWithWeappCookie") 什么的
然后新增的 wx.requestWithWeappCookie方法，就不overwrite 微信自己的request了

这里有相关讨论
https://developers.weixin.qq.com/community/develop/doc/000cc0f0c70250ea51e6faa6156400

**Comment by charleslo1** [comment]
谢谢反馈，新版已经修复了这个问题，你也可以在插件环境下直接使用内置别名 wx.requestWithCookie，也可以使用 cookies.config 方法配置自定义别名：

```
import cookies from 'weapp-cookie'

// 使用内置别名
wx.requestWithCookie({
    url: 'https://example.com/user/current',
    success: function (res) {
        console.log(res)
    }
})

// 配置自定义别名
cookies.config({ requestAlias: 'requestx' })

// 使用自定义别名
wx.requestx({
    url: 'https://example.com/user/current',
    success: function (res) {
        console.log(res)
    }
})
```
